# Generated by Django 2.2 on 2021-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('sign', models.CharField(max_length=50, verbose_name='个人签名')),
                ('info', models.CharField(max_length=150, verbose_name='个人描述')),
                ('avatar', models.ImageField(upload_to='photo', verbose_name='头像')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
